version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app52921"
s3_bucket = "mysamapps2021"
s3_prefix = "app52921"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"